<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>DEVELOPERS SAC</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.4.1/css/bulma.css">
</head>
<body>
<div class="columns is-mobile">
    <div class="column is-half is-offset-one-quarter">

        <nav class="nav">
            <div class="nav-left">
                <a class="nav-item">
                    DEVELOPERS SAC
                </a>
            </div>

            <div class="nav-center">
                <a class="nav-item">
                </a>
            </div>

            <!-- This "nav-toggle" hamburger menu is only visible on mobile -->
            <!-- You need JavaScript to toggle the "is-active" class on "nav-menu" -->
            <span class="nav-toggle">
    <span></span>
    <span></span>
    <span></span>
  </span>

            <!-- This "nav-menu" is hidden on mobile -->
            <!-- Add the modifier "is-active" to display it on mobile -->
            <div class="nav-right nav-menu">
                <div class="nav-item">
                    <i>Checkout the repo</i>
                    <span class="icon">
        <i class="fa fa-github"></i>
      </span>
                </div>
            </div>
        </nav>
        <section class="section">
            <div class="container">
            </div>
        </section>


    </div>
</div>
</body>
</html>
